//Partially generated by ChatGPT

document.addEventListener("DOMContentLoaded", () => {
    const cards = document.querySelectorAll(".skill-card");
    const buttons = document.querySelectorAll(".filter-buttons button");

    // Convert DOM cards into data objects
    const skills = Array.from(cards).map(card => ({
        element: card,
        category: card.dataset.category
    }));

    buttons.forEach(button => {
        button.addEventListener("click", () => {
            const category = button.dataset.category;

            // Get filtered results
            const filteredSkills = filterSkillsByCategory(skills, category);

            // Hide all cards first
            skills.forEach(skill => {
                skill.element.style.display = "none";
            });

            // Show only filtered cards
            filteredSkills.forEach(skill => {
                skill.element.style.display = "block";
            });
        });
    });
});